plugins {
    id 'java'
}

group = mod_group_id
version = mod_version
description = mod_description

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

jar {
    archiveBaseName.set(mod_id)
    manifest {
        attributes(
                'Implementation-Title': mod_name,
                'Implementation-Version': version,
                'Implementation-Vendor': mod_authors,
                'Implementation-URL': home_url
        )
    }
}
