modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "MIT License"
showAsResourcePack = false

[[mods]]
modId = "compasscleaner"
version = "1.20.6-2.0.1"
displayName = "Compass Cleaner"
displayURL = 'https://modrinth.com/user/spekarchik'
logoFile = "pack.png"
authors = "Sergey Pekarchik"
description = "A simple mod that allows you to easily demagnetize compasses using a straightforward crafting recipe.\nKeeps your inventory organized by preventing confusion between magnetized and regular compasses."

[[dependencies.compasscleaner]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.5,1.21)"
ordering="NONE"
side = "BOTH"
