modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "${mod_license}"
showAsResourcePack = false

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${home_url}"
logoFile = "${logo}"
authors = "${mod_authors}"
description = "${mod_description}"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${min_minecraft_version},)"
ordering="NONE"
side = "${mod_side}"
